### ISSUE TITLE
add epic games

### ISSUE THREAD

**Issue by rbcoder117** [Botspot/pi-apps#1395]
### What is the name of the app?

epic games

### (Optional) Where is the app hosted?

[here](https://www.epicgames.com/store/en-US/download)

### About the app

it is a launcher for many popular games such as fortnite and the awesome game making engine unreal.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.
I have no experience in deb files.

**Comment by GYKgamer** [comment]
It wouldn't work as epic games launcher doesn't work in arm64 cpus

**Comment by DatBoiG265** [comment]
you could try installing the epic games launcher useing wine but the hardware limitations on the raspberry pi wont let it run any games

**Comment by itsdarklikehell** [comment]
there is heroic.
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher
but im not sure if it runs on arm.

**Comment by GYKgamer** [comment]
will test rn

**Comment by GYKgamer** [comment]
![image](https://user-images.githubusercontent.com/41442793/155828299-da6cfa35-c008-406c-beb8-510c1f287554.png)
no sign of arm64 sadly

**Comment by rbcoder117** [comment]
Oh, ok

**Comment by theofficialgman** [comment]
closing as this is really too much work for pi-apps and not really in its scope. steam exists mostly because its a well supported platform for running games on linux natively, only requiring x86 -> arm translation
