### ISSUE TITLE
PiOS Bookworm Incompatibilities

### ISSUE THREAD

**Issue by theofficialgman** [Botspot/pi-apps#2401]
Apps with known compatibility issues (installing or running) on Bookworm that need to be fixed in no particular order

Uses pip:
- [x] CommanderPi
- [x] Powerline Shell https://github.com/Botspot/pi-apps/actions/runs/5674579997/job/15378383497#step:3:1184
- [x] PiGro
- [x] Quartz https://github.com/Botspot/pi-apps/actions/runs/5674580679/job/15378397179#step:3:1195
- [x] BlockPi (removed) (upstream https://github.com/alienzhangyw/BlockPi/issues/15 ) https://github.com/Botspot/pi-apps/actions/runs/5674572818/job/15378360281#step:3:1132
- [x] Pi-Apps Terminal Plugin (python) (removed)
- [x] Email Checker (removed) https://github.com/Botspot/pi-apps/actions/runs/5674575175/job/15378372480#step:3:1177
- [x] Sysmon (removed) (upstream https://github.com/t0xic0der/sysmon/issues/52 ) https://github.com/Botspot/pi-apps/actions/runs/5674582104/job/15378394996#step:3:1179

Other errors:
- [x] Prusaslicer (https://github.com/davidk/PrusaSlicer-ARM.AppImage/issues/29)
- [x] Stunt Rally (disabled, see https://github.com/Botspot/pi-apps/issues/2160)  https://github.com/Botspot/pi-apps/actions/runs/5674581872/job/15378396902#step:3:1256
- [ ] VeraCrypt (upstream https://github.com/veracrypt/VeraCrypt/issues/1046) https://github.com/Botspot/pi-apps/actions/runs/5674583305/job/15378399222#step:3:1212
- [x] KeePassXC https://github.com/Botspot/pi-apps/actions/runs/5674576980/job/15378423712#step:3:1212
- [x] Lokinet (already disabled) https://github.com/Botspot/pi-apps/actions/runs/5674577731/job/15378421562#step:3:1182
- [x] Marathon https://github.com/Botspot/pi-apps/actions/runs/5674577904/job/15378418240#step:3:2880
- [x] AstroMenace https://github.com/Botspot/pi-apps/actions/runs/5674572478/job/15378359527#step:3:2170
- [x] BlueJ Java IDE (upstream PiOS) https://github.com/k-pet-group/BlueJ-Greenfoot/issues/2249
- [x] Flow browser: runtime dependency issues (`libwebp.so.6` not available on bookworm) and potentially other issues

note there are some apps in pi-apps that only use pip on older distros (to get newer versions of packages), these apps are fine since they won't use pip on bookworm and are not included in this list

(developers feel free to edit this list and checkoff items as they are fixed as well as add more categories for other incompatabilities)

**Comment by theofficialgman** [comment]
bluej java ide also has a bug that can only be fixed upstream since the deb itself depends on `openjdk-11-jdk`
```
Installing BlueJ Java IDE...

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 bluej : Depends: openjdk-11-jdk (>= 11) but it is not installable
         Depends: libopenjfx-java (>= 11) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Failed to install BlueJ Java IDE!
```

**Comment by theofficialgman** [comment]
`bluej` package has been by piOS devs since it did not work on bookworm. now it won't show in pi-apps list and is thus not an issue anymore.

long term investigate packaging ourselves new versions if someone really wants this

**Comment by Botspot** [comment]
> bluej package has been by piOS devs
Did you mean to say it has been *removed* by the devs?

**Comment by theofficialgman** [comment]
> Did you mean to say it has been _removed_ by the devs?

nah just "has been by the devs". Implying that the devs made the package only exist in the past....
yes I meant to write removed

**Comment by theofficialgman** [comment]
@Botspot bookworm's chromium does not appear to work with chrome sync from better chromium
I checked and believe that the environment variables are getting picked up. Are you able to confirm or deny if it works for you or not?

**Comment by Botspot** [comment]
> @Botspot bookworm's chromium does not appear to work with chrome sync from better chromium I checked and believe that the environment variables are getting picked up. Are you able to confirm or deny if it works for you or not?

I think a while back in the forums a dev raised the idea of disabling sync from their sourcecode since it didn't work at the time. It's possible that change was implemented but its effects were delayed.
I will flash a new card with Bookworm and try it. It is also possible Debian was given a new key and we just need to update it.

**Comment by theofficialgman** [comment]
the keys are certainly still good. We use the same ones at switchroot (on chromium 112 because its hard to build chromium on bionic so we don't update every version) and I just checked and no issues.

**Comment by theofficialgman** [comment]
@Botspot I checked the debian bookworm deb and indeed the `GOOGLE_DEFAULT_CLIENT_ID` and `GOOGLE_DEFAULT_CLIENT_SECRET` have changed.

that means that google is likely doing server side checks on what version the browser is running (looking at the user agent) and disallowing the old keys on newer browser versions. both debian bullseye and bookworm are on chromium 115 now and use the new keys. piOS bookworm is also on chromium 115

**Comment by theofficialgman** [comment]
I will check and see if the new keys work on both older browser and 115 or if we need to do detection to add the correct keys

**Comment by theofficialgman** [comment]
new keys don't work on piOS bookworm either. I made a mistake above though. piOS bookworm is only on chromium 113, not 115. debian bullseye and bookworm are on 115, that was correct.

**Comment by theofficialgman** [comment]
@Botspot not working in piOS bullseye either (also on chromium 113). they updated to that in May. Maybe it has been broken since then?

**Comment by Botspot** [comment]
Nothing obvious seems to have broken it in their most recent May commit. https://github.com/RPi-Distro/chromium-browser/commit/02890bf553fc6ec5b50d5786f6fb5a1bb9a5c452#diff-cdb69093f12e3e227e964a5803793eb7a4f4c6a0fbf153997e2b1097896e3257

**Comment by Botspot** [comment]
@theofficialgman, in your testing, did you get as far as the google.com sign-in page for chrome sync?
![image](https://github.com/Botspot/pi-apps/assets/54716352/23f145bb-56b1-4a30-bd8c-19e4b9e93d46)
I did after several changes. Not sure which of those changes are necessary and I will begin to backtrack. But I am interested to know if you got to this point.

**Comment by theofficialgman** [comment]
> @theofficialgman, in your testing, did you get as far as the google.com sign-in page for chrome sync?

no, the "turn on sync" button is actually just totally missing. I just tried clicking "add" at the bottom and then sign in and then always got an error code.

**Comment by Botspot** [comment]
OK first you need to go to chrome://settings/syncSetup and "allow chromium sign-in". then relaunch the browser and it should be possible to reach where I am.

However, I got this error in the terminal after signing in to google: 
```
[203077:203077:0731/214705.345808:ERROR:turn_sync_on_helper.cc(243)] Cannot turn Sync On for invalid account.
```

**Comment by Botspot** [comment]
That error is solved by reverting to the current `apikeys` file in Better Chromium. The `Cannot turn Sync On for invalid account.` error only occurred on my Bullseye system when using the latest Debian apikeys values.
Sync appears to work for me without any script changes, although enabling that obscure setting in the UI is a necessary first step.

**Comment by theofficialgman** [comment]
just figure out what file it edits when enabling that in the UI
chromium/chrome has lots of config files were you can set default options.

**Comment by theofficialgman** [comment]
@Botspot its piOS devs.... https://github.com/RPi-Distro/chromium-browser/blob/master/debian/patches/0017-disable-browser-sign-in-feature-by-default.patch

**Comment by theofficialgman** [comment]
ok we can do this and it will work:
https://stackoverflow.com/questions/67689442/turn-off-chrome-signin-with-selenium-programmatically

we just can't change the system profile because the piOS dev chromium patch always sets it to false for new user creation

**Comment by Botspot** [comment]
> we just can't change the system profile because the piOS dev chromium patch always sets it to false for new user creation

I had assumed that those registry changes were just adding lines to their rpi-chromium-mods /etc/chromium/master_preferences file, but I do not see those lines there.
By using `meld` alongside `jq` before and after changing that setting, I confirmed that this section in the Preferences file is changed:
```
  "signin": {
    "AccountReconcilor": {
      "kDiceMigrationOnStartup2": true
    },
    "allowed": true,
    "allowed_on_next_startup": true
  },
```
when disabled:
```
"signin": {
    "AccountReconcilor": {
      "kDiceMigrationOnStartup2": true
    },
    "allowed": false,
    "allowed_on_next_startup": false
  },
```
According to chatgpt, selenium webdriver is only accessible from writing a compiled program. Not sure if that is true or not, but it seems like excessive effort if true.

**Comment by theofficialgman** [comment]
this is what I plan on adding
```bash
  [ -f "$HOME/.config/chromium/Default/Preferences" ] && ( sed -i 's/"signin":{"allowed":false}/"signin":{"allowed":true,"allowed_on_next_startup":true}/g' "$HOME/.config/chromium/Default/Preferences"; sed -i 's/"signin":{"allowed":false,"allowed_on_next_startup":false}/"signin":{"allowed":true,"allowed_on_next_startup":true}/g' "$HOME/.config/chromium/Default/Preferences"; )
```
its the only way to change the value for the Default user when it is already created is to actually change that file. this is the same thing as clicking the toggle button.

**Comment by theofficialgman** [comment]
> selenium webdriver

wth is chatgpt talking about? what is selenium webdriver?

**Comment by Botspot** [comment]
> > selenium webdriver
> 
> wth is chatgpt talking about? what is selenium webdriver?

![image](https://github.com/Botspot/pi-apps/assets/54716352/a8d3b7c6-8ca0-4cba-90a9-c8e3492b3a41)

**Comment by Botspot** [comment]
> its the only way to change the value for the Default user when it is already created is to actually change that file. this is the same thing as clicking the toggle button.

That seems to be correct, as changing master_preferences had none effect. I will take this from here. I will make it apply to all profiles and re-run on every chromium launch similar to how I did it for `reduce_writes`.

**Comment by theofficialgman** [comment]
too late I already pushed.

> I will make it apply to all profiles 

that is harder than you think. the folder that contains `Default` also contains many other folders. so you can't simply work on every folder and I am not sure if its safe to operate on other users.

> and re-run on every chromium launch similar to how I did it for `reduce_writes`.

thats kinda gross but I get desire. We should probably just ask piOS to not be so invasive with their patch. they should be able to ship those defaults as part of their config I think and not touch the code.

**Comment by Botspot** [comment]
I have pushed my implementation in commit https://github.com/Botspot/pi-apps/commit/681b3ffae64b84df56473bbd55af0ab70efeb416.

**Comment by sudo-splinter-cell** [comment]
Thanks for all the work you do for Chromium sync. It is something that i can't live without under RPI. All my bookmarks and passwords to all my online accounts, basically my gateway to the internet. We don't really have much of a choice when it comes to web browsers under RPI OS. I think now they also "modified" Firefox in bookworm to make it snappier and better with video-playback, which is good news, but of course without widewine support, we still need Chromium. Maybe if this wasn't an issue, i would be willing to migrate to Firefox. Thanks anyway.
