### ISSUE TITLE
Meta Issue: Upstream Armbian Bugs (not a pi-apps issue)

### ISSUE THREAD

**Issue by theofficialgman** [Botspot/pi-apps#2642]
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Issues with Upstream Armbian prevent the installation and/or upgrades for some applications

### Description

This is a meta issue for many of the pi-apps logs we have been sent in roughly the past year related to BAD armbian packages (mostly due to broken multiarch).

I am the co-maintainer of pi-apps and am CCing all relevant armbian developers related to such packages. The armbian developers have not indicated themselves as maintainers or uploaders in the control file of the packages that they are responsible for.

The logs are pi-apps formatted logs that were sent to our discord via our error report system without pi-apps. Where relevant, they provide additional developer diagnostic logs that will help you (the Armbian developers) resolve your packaging issues.

[install-fail-Minecraft_Bedrock.txt](https://github.com/user-attachments/files/16894820/install-fail-Minecraft_Bedrock.txt)
[install-fail-Steam.txt](https://github.com/user-attachments/files/16894870/install-fail-Steam.txt)
[install-fail-Steam(1).txt](https://github.com/user-attachments/files/16894872/install-fail-Steam.1.txt)
[install-fail-Box86.txt](https://github.com/user-attachments/files/16894873/install-fail-Box86.txt)
[install-fail-Box86(1).txt](https://github.com/user-attachments/files/16894889/install-fail-Box86.1.txt)

CC: @efectn @alexl83 @Janmcha @StephenGraf @chraac @amazingfate @prahal @brentr @linhz0hz @rpardini @krachlatte @joekhoobyar @ZazaBR @clee @vamzii @catalinii

As mentioned, the offending improperly packages/provided packages are not correctly marked with their real maintainer so I am unable to notify the correct person(s). If I have missed someone that should be notified please ping them in a comment.

### What are your system specs (run the following command in your terminal)?

```bash
N/A
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
See above
```

**Comment by amazingfate** [comment]
The apt error is because of version of arm64 and armhf mesa not matching.
run `apt-cache policy libegl-mesa0` to see where these packages come from. Armbian does add some third-party repos provding packages like mesa, and each board may have different thirdparty repo.

**Comment by theofficialgman** [comment]
> The apt error is because of version of arm64 and armhf mesa not matching. run `apt-cache policy libegl-mesa0` to see where these packages come from. Armbian does add some third-party repos provding packages like mesa, and each board may have different thirdparty repo.

@amazingfate the apt-cache policy output you requested is already in the logfiles, scroll and you will see it. These logs are not from myself but users that have reported them through or discord error report system as already explained. armbian ships these repos so it is your job to vet them and make sure they do not cause such issues as missing multiarch (armhf packages on arm64 system) packages.

**Comment by theofficialgman** [comment]
I appreciate you trying to diagnose the issues. I already diagnosed each one as we received them.

Please check the current version of `linux-libc-dev` in the repositories for armbian bookworm and jammy for all the hardware where custom versions are shipped and verify that the `/usr/share/doc/linux-libc-dev/changelog.Debian.gz` and all other shared files between the armhf and arm64 versions of the package are identical. The issue occurred because in both of those cases the files were not identical. We (at pi-apps) have blocked further instances of this error from being reported to us as of 3 weeks ago https://github.com/Botspot/pi-apps/commit/368f6e3f040a40ecd88e14f8cee4215d52e9d5f4 and automatically instruct users to contact their distro maintainer for such issues.

Your diagnosis for `install-fail-Box86(1).txt` is incorrect. The issue is that a custom `libharfbuzz0b:armhf` package is available for arm64 with no matching armhf version `6.0.0+dfsg-3+j`
```
Package: libharfbuzz0b
Priority: optional
Section: libs
Installed-Size: 954
Maintainer: أحمد المحمودي (Ahmed El-Mahmoudy) <aelmahmoudy@users.sourceforge.net>
Architecture: arm64
Source: harfbuzz
Version: 6.0.0+dfsg-3+j
Replaces: libharfbuzz0, libharfbuzz0a
Depends: libc6 (>= 2.33), libfreetype6 (>= 2.11.0), libglib2.0-0 (>= 2.31.8), libgraphite2-3 (>= 1.2.2)
Conflicts: libharfbuzz0, libharfbuzz0a
Filename: pool/jammy-desktop/h/harfbuzz/libharfbuzz0b_6.0.0+dfsg-3+j_arm64.deb
Size: 416552
MD5sum: 1fd883c26ac9ca159c09c7efc5a511fb
SHA1: cca0d2c3a495d92fd8c28699a72d4b874988ddd2
SHA256: 56461638025afe4705d089fcb0654b379fc720d95bbd2daa70a094f0b0f77bb3
SHA512: 56bd0b971559900857971ac1d1cad1db9fe01ed7fb0f3a5ddacfeddaeb7116d3a614f5fe728f7dc6c48d84fd16e7cbcff2e042655d660a26340521af0c140a14
Description: OpenType text shaping engine (shared library)
Description-md5: c01a2a5a6349f465ee349884ac4d8667
Homepage: https://www.freedesktop.org/wiki/Software/HarfBuzz
Multi-Arch: same
```

**Comment by theofficialgman** [comment]
As for this error report `install-fail-Steam(1).txt`, our logs do not provide the reason for why the issue occurs. I assume that the system has some preinstalled pin priority for the following repo
`Hit:4 https://ppa.launchpadcontent.net/liujianfeng1994/rockchip-multimedia/ubuntu noble InRelease`
that is preventing proper installation of `libgstreamer-plugins-base1.0-0` but that is just a guess. The user that reported this had this issue pre-existing on their install before attempting to install anything from pi-apps.

**Comment by theofficialgman** [comment]
@amazingfate another same `libharfbuzz0b` reported just a few minutes ago. Same reason as I explained two messages above.
[install-fail-StepMania.txt](https://github.com/user-attachments/files/16902198/install-fail-StepMania.txt)

**Comment by amazingfate** [comment]
>Please check the current version of linux-libc-dev in the repositories for armbian bookworm and jammy for all the hardware where custom versions are shipped

Armbian no longer provide `linux-libc-dev` in its repo. Instead linux-libc-dev-${FLAVOR} like `linux-libc-dev-legacy-bcm2711` is provided.

>The issue is that a custom libharfbuzz0b package is available for arm64 with no matching armhf version 6.0.0+dfsg-3+j

This package is imported from my ppa https://launchpad.net/~liujianfeng1994/+archive/ubuntu/chromium with no armhf version. I will rebuild all libaries in this repo with armhf.

>I assume that the system has some preinstalled pin priority for the following repo
Hit:4 https://ppa.launchpadcontent.net/liujianfeng1994/rockchip-multimedia/ubuntu noble InRelease
that is preventing proper installation of libgstreamer-plugins-base1.0-0 but that is just a guess.

That's not the root cause, installing `libgstreamer-plugins-base1.0-0` from ubuntu's repo also failed.
```
# apt install libgstreamer-plugins-base1.0-0=1.24.2-1ubuntu0.1 libgstreamer-plugins-base1.0-0:armhf=1.24.2-1ubuntu0.1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgstreamer-plugins-base1.0-0:armhf : Depends: libdrm2:armhf (>= 2.4.74) but it is not installable
```
libdrm2 is installed from https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers. But This repo is not in the image.
Oibaf is a staging repo which updates all the time so we have replaced it with new ppa https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa some times ago.
I have nightly image with kisak repo downloaded from https://github.com/armbian/os/releases and it has no such issue.

**Comment by rpardini** [comment]
I wonder if `SKIP_ARMBIAN_REPO=yes` CLI images built from source also suffer from problems?

**Comment by amazingfate** [comment]
> I wonder if `SKIP_ARMBIAN_REPO=yes` CLI images built from source also suffer from problems?

If armbian's repo is disabled, at least linux-libc-dev and harfbuzz related issues should not happen.

**Comment by amazingfate** [comment]
armhf harfbuzz pacakges are updated at armbian's beta repo: https://netcup.armbian.com/beta/pool/jammy-desktop/h/harfbuzz/

**Comment by amazingfate** [comment]
Armbian default repo already has harfbuzz
```
$ apt-cache policy libharfbuzz0b:armhf
libharfbuzz0b:armhf:
  已安装：(无)
  候选： 6.0.0+dfsg-3+j1
  版本列表：
     6.0.0+dfsg-3+j1 500
        500 http://apt.armbian.com jammy/jammy-desktop armhf Packages
     2.7.4-1ubuntu3.1 500
        500 http://ports.ubuntu.com jammy-security/main armhf Packages
        500 http://ports.ubuntu.com jammy-updates/main armhf Packages
     2.7.4-1ubuntu3 500
        500 http://ports.ubuntu.com jammy/main armhf Packages
```

**Comment by theofficialgman** [comment]
Here is another error we get from armbian frequently. Failures to install the snap store. This might indicate missing required kernel modules.

[install-fail-Snap_Store.txt](https://github.com/user-attachments/files/16979601/install-fail-Snap_Store.txt)
[install-fail-Snap_Store(1).txt](https://github.com/user-attachments/files/16979623/install-fail-Snap_Store.1.txt)

**Comment by amazingfate** [comment]
Armbian's repo still has issue syncing harfbuzz packages, we are looking at it.
I'm the maintainer of xiaomi pad5 pro, but I never use snap. I will look into it.
